# docker-compose.yml

services:
  # Первый экземпляр
  encoder1:
    build:
      context: .
      dockerfile: dockerfile.service
    ports:
      - "8260:8260"
    volumes:
      # Общая папка для моделей
      - ./models:/app/models
      # Отдельная папка для логов первого сервиса
      - ./logs/encoder1:/app/logs
    env_file:
      - .env          # параметры, общие для всех сервисов
      - .env.encoder1 # специфические параметры первого сервиса
    environment:
      - PORT=8260
      - DOCKER_ENV=true
    container_name: encoder_service_1
    restart: unless-stopped
    command: >
      uvicorn encoder_service.main:app
      --port 8260 --host 0.0.0.0 --workers 1
      --lifespan on --timeout-graceful-shutdown 15
    init: true
    shm_size: '2gb'
    mem_limit: 8g
    cpus: '4.0'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Второй экземпляр
  encoder2:
    build:
      context: .
      dockerfile: dockerfile.service
    ports:
      - "8261:8261"
    volumes:
      # Общая папка для моделей
      - ./models:/app/models
      # Отдельная папка для логов второго сервиса
      - ./logs/encoder2:/app/logs
    env_file:
      - .env          # параметры, общие для всех сервисов
      - .env.encoder2 # специфические параметры второго сервиса
    environment:
      - PORT=8261
      - DOCKER_ENV=true
    container_name: encoder_service_2
    restart: unless-stopped
    command: >
      uvicorn encoder_service.main:app
      --port 8261 --host 0.0.0.0 --workers 1
      --lifespan on --timeout-graceful-shutdown 15
    init: true
    shm_size: '2gb'
    mem_limit: 8g
    cpus: '4.0'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]